#!/bin/bash
# This file was not written by hand. This file is not intended to be edited by
# hand. If you think you need to edit this by hand, you don't.

cat > clodsire << applaud
#!/bin/bash
if command -v readlink &> /dev/null
then
    SCRIPT=\$(readlink -f \$0)
    cp \$SCRIPT /usr/local/bin/weboff || echo "Ignore above error if it's about weboff being the same as weboff"
else
    cp /etc/clodsire /usr/local/bin/weboff
fi

iptables -P INPUT ACCEPT
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

iptables -F INPUT
iptables -F OUTPUT

iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
applaud
read -p "Enter host (virt_debian,virt_ubuweb,virt_ubuwkst,virt_centos,virt_splunk,virt_fedora,hard_debian,hard_zen,hard_emr,hard_onion,hard_iot,hard_ubuwkst):" CLODSIRE_HOST
case $CLODSIRE_HOST in
virt_debian)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
applaud
;;
virt_ubuweb)
cat >> clodsire << applaud
iptables -A INPUT -p tcp -s 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.100 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.20 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.30 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.40 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.10 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.200 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
applaud
;;
virt_ubuwkst)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
applaud
;;
virt_centos)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
applaud
;;
virt_splunk)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.150 --dport 514 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.10 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.100 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.20 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.30 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.40 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.10 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.200 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.10 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.10 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.100 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.20 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.30 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.40 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.10 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.200 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.10 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 9997 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 8000 -j ACCEPT
applaud
;;
virt_fedora)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 25 -j ACCEPT
iptables -A INPUT -p tcp --dport 110 -j ACCEPT
applaud
;;
hard_debian)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
applaud
;;
hard_zen)
cat >> clodsire << applaud
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 8000 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
applaud
;;
hard_emr)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
applaud
;;
hard_onion)
cat >> clodsire << applaud
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.20 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.100 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.200 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.10 --dport 8000 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 8089 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.23 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.5 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.97 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.201 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.101 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.240.11 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.241.27 --dport 9997 -j ACCEPT
iptables -A INPUT -p tcp -s 172.20.242.102 --dport 9997 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
applaud
;;
hard_iot)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
applaud
;;
hard_ubuwkst)
cat >> clodsire << applaud
iptables -A INPUT -p udp -s 172.20.242.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.100 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.20 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.30 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.40 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.200 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.23 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.5 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.97 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.10 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.201 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.101 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.240.11 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.27 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.242.102 --dport 161 -j ACCEPT
iptables -A INPUT -p udp -s 172.20.241.20 --dport 161 -j ACCEPT
applaud
;;
esac
cat >> clodsire << applaud
iptables -A INPUT -m limit --limit 15/minute -j LOG --log-level 4 --log-prefix 'FW DROP [in]: '
iptables -A INPUT -j DROP
applaud
cat >> clodsire << applaud
cat > /usr/local/bin/webon << EOF
iptables -F OUTPUT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
applaud
case $CLODSIRE_HOST in
virt_debian)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
virt_ubuweb)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
virt_ubuwkst)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
virt_centos)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
virt_splunk)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
applaud
;;
virt_fedora)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 389 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 636 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
hard_debian)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
hard_zen)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
hard_emr)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
hard_onion)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
hard_iot)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
hard_ubuwkst)
cat >> clodsire << applaud
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 9997 -j ACCEPT
applaud
;;
esac
cat >> clodsire << applaud
EOF
chmod +x /usr/local/bin/webon
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
applaud
case $CLODSIRE_HOST in
virt_debian)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.30 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.11 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.23 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.97 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.201 --dport 80 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 53 -j ACCEPT
applaud
;;
virt_ubuweb)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 53 -j ACCEPT
applaud
;;
virt_ubuwkst)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.30 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.11 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.23 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.97 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.201 --dport 80 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.242.150 --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.242.150 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.242.150 --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 53 -j ACCEPT
applaud
;;
virt_centos)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 53 -j ACCEPT
applaud
;;
virt_splunk)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 53 -j ACCEPT
applaud
;;
virt_fedora)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.242.200 --dport 389 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.242.200 --dport 636 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 53 -j ACCEPT
applaud
;;
hard_debian)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.30 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.11 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.23 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.97 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.201 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.27 --dport 53 -j ACCEPT
applaud
;;
hard_zen)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.27 --dport 53 -j ACCEPT
applaud
;;
hard_emr)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.27 --dport 53 -j ACCEPT
applaud
;;
hard_onion)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.30 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.11 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.23 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.97 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.201 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.27 --dport 53 -j ACCEPT
applaud
;;
hard_iot)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.27 --dport 53 -j ACCEPT
applaud
;;
hard_ubuwkst)
cat >> clodsire << applaud
iptables -A OUTPUT -p tcp -d 172.20.242.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.20 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.30 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 8089 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.10 --dport 9997 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.11 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.23 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.97 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.241.201 --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.20.240.5 --dport 8000 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.100 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.30 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.20 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.40 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.23 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.5 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.240.97 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.10 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.201 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.101 --dport 161 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.242.200 --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp -d 172.20.241.27 --dport 53 -j ACCEPT
applaud
;;
esac
cat >> clodsire << applaud
iptables -A OUTPUT -m limit --limit 15/minute -j LOG --log-uid --log-level 4 --log-prefix 'FW DROP [out]: ACTION=DROP'
iptables -A OUTPUT -j DROP
applaud
