#!/bin/bash
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

iptables -F
iptables -N DROP_LOG
##### INPUT CHAIN #####

# All systems
iptables -A INPUT -i lo               -j ACCEPT  # Allow all localhost traffic

# Allow traffic from everything on the topology

iptables -A INPUT -s 172.20.240.10  -j ACCEPT
iptables -A INPUT -s 172.20.240.20  -j ACCEPT
iptables -A INPUT -s 172.20.240.11  -j ACCEPT
iptables -A INPUT -s 172.20.240.23  -j ACCEPT
iptables -A INPUT -s 172.20.240.5   -j ACCEPT
iptables -A INPUT -s 172.20.240.97  -j ACCEPT

iptables -A INPUT -s 172.20.241.20  -j ACCEPT
iptables -A INPUT -s 172.20.241.30  -j ACCEPT
iptables -A INPUT -s 172.20.241.40  -j ACCEPT
iptables -A INPUT -s 172.20.241.3   -j ACCEPT
iptables -A INPUT -s 172.20.241.27  -j ACCEPT
iptables -A INPUT -s 172.20.241.201 -j ACCEPT
iptables -A INPUT -s 172.20.241.100 -j ACCEPT

iptables -A INPUT -s 172.20.242.10  -j ACCEPT
iptables -A INPUT -s 172.20.242.20  -j ACCEPT
iptables -A INPUT -s 172.20.242.10  -j ACCEPT
iptables -A INPUT -s 172.20.242.190 -j ACCEPT 
iptables -A INPUT -s 172.20.242.180 -j ACCEPT 
iptables -A INPUT -s 172.20.242.200 -j ACCEPT

iptables -A INPUT -s 172.20.241.254 -j ACCEPT
iptables -A INPUT -s 172.20.242.150 -j ACCEPT
iptables -A INPUT -s 172.20.240.254 -j ACCEPT
iptables -A INPUT -s 172.20.242.254 -j ACCEPT

iptables -A INPUT -s 172.20.0.0/16 -j DROP_LOG # Drop and log rouges

iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT # Allow important traffic
# Fedora
iptables -A INPUT -p tcp --dport 25   -j ACCEPT # Allow SMTP
iptables -A INPUT -p tcp --dport 110  -j ACCEPT # Allow POP3

# CentOS
iptables -A INPUT -p tcp --dport 80   -j ACCEPT # Allow HTTP
iptables -A INPUT -p tcp --dport 443  -j ACCEPT # Allow HTTPS

# Splunk
iptables -A INPUT -p tcp --dport 8000 -j ACCEPT # Allow Splunk Web

# Debian
iptables -A INPUT -p udp --dport 53   -j ACCEPT # Allow DNS

# All systems
iptables -A INPUT -m limit --limit 15/minute -j LOG --log-level 6 --log-prefix 'FW DROP [in]: '
iptables -A INPUT -p tcp -j DROP # Deny ANY:ANY


##### OUTPUT CHAIN #####

iptables -A OUTPUT -o lo            -j ACCEPT  # Allow all localhost traffic

# Allow known inbound topology

cat << EOF > /usr/bin/weboff
#!/bin/bash
##### OUTPUT CHAIN #####

iptables -A OUTPUT -o lo            -j ACCEPT  # Allow all localhost traffic

# Allow known inbound topology

iptables -A OUTPUT -d 172.20.240.10  -j ACCEPT
iptables -A OUTPUT -d 172.20.240.20  -j ACCEPT
iptables -A OUTPUT -d 172.20.240.11  -j ACCEPT
iptables -A OUTPUT -d 172.20.240.23  -j ACCEPT
iptables -A OUTPUT -d 172.20.240.5   -j ACCEPT
iptables -A OUTPUT -d 172.20.240.97  -j ACCEPT

iptables -A OUTPUT -d 172.20.241.20  -j ACCEPT
iptables -A OUTPUT -d 172.20.241.30  -j ACCEPT
iptables -A OUTPUT -d 172.20.241.40  -j ACCEPT
iptables -A OUTPUT -d 172.20.241.3   -j ACCEPT
iptables -A OUTPUT -d 172.20.241.27  -j ACCEPT
iptables -A OUTPUT -d 172.20.241.201 -j ACCEPT
iptables -A OUTPUT -d 172.20.241.100 -j ACCEPT

iptables -A OUTPUT -d 172.20.242.10  -j ACCEPT
iptables -A OUTPUT -d 172.20.242.20  -j ACCEPT
iptables -A OUTPUT -d 172.20.242.10  -j ACCEPT
iptables -A OUTPUT -d 172.20.242.190 -j ACCEPT 
iptables -A OUTPUT -d 172.20.242.180 -j ACCEPT 
iptables -A OUTPUT -d 172.20.242.200 -j ACCEPT

iptables -A OUTPUT -d 172.20.241.254 -j ACCEPT
iptables -A OUTPUT -d 172.20.242.150 -j ACCEPT
iptables -A OUTPUT -d 172.20.240.254 -j ACCEPT
iptables -A OUTPUT -d 172.20.242.254 -j ACCEPT

iptables -A OUTPUT -d 172.20.0.0/16 -j DROP_LOG # Drop and log rouges

iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT # Don't break services like Splunk

iptables -A OUTPUT -m limit --limit 15/minute -j LOG --log-level 6 --log-prefix 'FW DROP [out]: '
iptables -A OUTPUT -j DROP
EOF

chmod +x /usr/bin/weboff
. /usr/bin/weboff
iptables -A DROP_LOG -m limit --limit 15/minute -j LOG --log-level 6 --log-prefix 'FW DROP [rouge]: '
iptables -A DROP_LOG -j DROP

cat << EOF > /usr/bin/webon
#!/bin/bash
iptables -F OUTPUT 
EOF

cat << EOF > /usr/bin/webdo
#!/bin/bash
webon
$@
weboff
EOF

cat << EOF > /usr/bin/boxdown
#!/bin/bash
iptables -F
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -j DROP
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -j DROP
EOF

cat << EOF > /usr/bin/boxup
#!/bin/bash
/etc/smartfw
EOF

chmod +x /usr/bin/webon
chmod +x /usr/bin/weboff
chmod +x /usr/bin/webdo
