---
- name: Doom
  become: true
  hosts: all
  become_user: chris

  tasks:
  - name: Make log
    file:
      path: /var/log/doom.log
      state: touch
      mode: '777'
    become_user: root

  - name: Install Doom and screen
    apt:
      name: screen,prboom-plus-game-server
      state: present

  - name: Start screen
    shell: screen -L /var/log/doom.log -dmS doom bash

  - name: Setup log
    shell: screen -S doom -X colon "logfile flush 0^M"
  
  - name: Start doom
    shell: screen -S doom -X stuff 'prboom-plus-game-server\n'