all:
  children:
    client:
      hosts:
        workstation:
          ansible_become_password: changeme
          ansible_host: localhost
          ansible_port: 22
          ansible_ssh_private_key_file: /home/chris/.ssh/ansible
          ansible_user: ansible
          ports: &id001
            dns:
            - 53
            http:
            - 80
            https:
            - 443
            mail:
            - 25
            - 143
            - 465
            - 110
            mysql:
            - 3306
            ntp:
            - 123
            splnk:
            - 8000
            - 8089
            - 9997
    dns:
      hosts:
        deb-dns:
          ansible_become_password: changeme
          ansible_host: 172.20.240.23
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/ansible
          ansible_user: ansible
          ports: *id001
          splunkIp: 172.20.241.3
        ubu-dns:
          ansible_become_pass: '!Password123'
          ansible_become_password: changeme
          ansible_host: 172.25.2<team>.10
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/ansible
          ansible_user: sysadmin
          ports: *id001
          splunkIp: 172.25.<team>.67
    http:
      hosts:
        centos:
          ansible_become_password: changeme
          ansible_host: 172.25.2<team>.30
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/ansible
          ansible_user: ansible
          ports: *id001
          splunkIp: 172.25.<team>.67
        fedora:
          ansible_become_password: changeme
          ansible_host: 172.25.2<team>.40
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/ansible
          ansible_user: ansible
          ports: *id001
          splunkIp: 172.25.<team>.67
        ubu-web:
          ansible_become_password: changeme
          ansible_host: 172.20.240.5
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/ansible
          ansible_user: ansible
          ports: *id001
          splunkIp: 172.20.241.3
    https:
      hosts:
        centos: {}
        fedora: {}
        ubu-web: {}
    mail:
      hosts:
        fedora: {}
    mysql:
      hosts:
        deb-dns: {}
        deb-mysql:
          ansible_become_password: changeme
          ansible_host: 172.25.2<team>.20
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/ansible
          ansible_user: ansible
          ports: *id001
          splunkIp: 172.25.<team>.67
    ntp:
      hosts:
        centos: {}
        deb-dns: {}
    servers:
      children:
        comm:
          hosts:
            centos: {}
            deb-mysql: {}
            fedora: {}
            phantom:
              ansible_become_password: changeme
              ansible_host: 172.25.2<team>.10
              ansible_port: 22
              ansible_ssh_private_key_file: /root/.ssh/ansible
              ansible_user: ansible
              ports: *id001
              splunkIp: 172.25.<team>.67
            splunk:
              ansible_become_password: changeme
              ansible_host: 172.25.2<team>.20
              ansible_password: changemenow
              ansible_port: 22
              ansible_ssh_private_key_file: /root/.ssh/ansible
              ansible_user: ansible
              ports: *id001
              splunkIp: 172.25.<team>.67
            ubu-dns: {}
        hard:
          hosts:
            deb-dns: {}
            onion:
              ansible_become_password: changeme
              ansible_host: 172.20.241.3
              ansible_port: 22
              ansible_ssh_private_key_file: /root/.ssh/ansible
              ansible_user: ansible
              ports: *id001
              splunkIp: 172.20.241.3
            pi:
              ansible_become_password: changeme
              ansible_host: 172.20.241.201
              ansible_port: 22
              ansible_ssh_private_key_file: /root/.ssh/ansible
              ansible_user: ansible
              ports: *id001
              splunkIp: 172.20.241.3
            ubu-emr:
              ansible_become_password: changeme
              ansible_host: 172.20.240.97
              ansible_port: 22
              ansible_ssh_private_key_file: /root/.ssh/ansible
              ansible_user: ansible
              ports: *id001
              splunkIp: 172.20.241.3
            ubu-web: {}
    splnk:
      hosts:
        splunk: {}
    ungrouped: {}
